export const CASE_GET_PRODUCTS = "GET_PRODUCTS";
export const CASE_GET_ONE_PRODUCT = "GET_ONE_PRODUCT";

export const CASE_GET_COMMENTS = "CASE_GET_COMMENTS";
export const CASE_GET_ONE_COMMENT = "CASE_GET_ONE_COMMENT";

export const CASE_GET_BRANDS = 'GET_BRANDS';

export const CASE_GET_CART = "GET_CART";
export const CASE_GET_WISH = "GET_WISH";

